VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "DIRSOUND"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Private mSndBuff() As Byte

Public Sub BufferRestore()

End Sub

Public Sub GetCurrentPosition(PosVal As Long)

End Sub
Public Sub SetLength(Length As Long)

End Sub
Public Function Length() As Long

End Function

Public Function BufferLock(N1 As Long, L As Long, w1 As Long, l1 As Long, w2 As Long, l2 As Long, N2 As Long) As Long

End Function

Public Function BufferUnlock(w1 As Long, l1 As Long, w2 As Long, l2 As Long)

End Function
